version: '3.8'

services:
  db-test:
    image: postgres:13
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
    ports:
      - "5432:5432"
    volumes:
      - db_test_data:/var/lib/postgresql/data

volumes:
  db_test_data:
