version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: src/main/docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/hr_management
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: your_password
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: hr_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend/HRManagementSystem
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "5000:80"

volumes:
  db_data:

