
#### docker-compose.yml


version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: src/main/docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/hr_management
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: your_password
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: hr_management
      MYSQL_ROOT_PASSWORD: your_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  frontend:
    build: ./frontend/HRManagementSystem
    depends_on:
      - backend
    ports:
      - "5000:80"

volumes:
  db_data:
